version: "3"

services:
  db_postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data:rw

volumes:
  # postgres data
  pg-data:

