
GET http://localhost:4444/not_exist HTTP/1.1

###

GET http://localhost:4444/hello HTTP/1.1

###

GET http://localhost:4444/users

###

GET http://localhost:4444/users/8

###

POST http://localhost:4444/users
Content-Type: application/json

{
    "id": 11111,
    "username": "FooBaz2",
    "email": "jhon@gmail.com2"
}

###

DELETE http://localhost:4444/users/1

