[package]
name = "diesel-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "^0", features = ["serde"] }
diesel = { version = "^2", features = ["chrono", "postgres"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
dotenv = { version = "^0" }
