version: "3"

services:
  auth-server:
    container_name: ${CONTAINER_NAME}
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data:rw

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pg-data:/var/lib/pgadmin:rw

volumes:
  # postgres data
  pg-data:

