version: "3"

services:
  database-diesel:
    container_name: postgres-container
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - diesel-demo:/var/lib/postgresql/data:rw

volumes:
  # postgres data
  diesel-demo:
